### ISSUE TITLE
Enable comma-separated multiValue options

### ISSUE THREAD

**Issue by pedrorijo91** [bmc/argot#13]
Sometimes it is a bit ugly to pass multiValue options with current syntax:

`sbt "run -x 1 -x 2 -x 3"`

Ain't it possible to add another 'type' of multiValue option that parses a comma-separated (or any other delimiter) parameter that would produce a List similar as the produced by the current approach?

Example:

`sbt "run -x 1,2,3"`

**Comment by bmc** [comment]
Closing this issue. Argot is now abandonware. [scopt](https://github.com/scopt/scopt) is more fully-featured and more immutable. That's what I'm switching to using.
