### ISSUE TITLE
Argot has an transitive dependency on jline and junit through grizzled-scala

### ISSUE THREAD

**Issue by jrudolph** [bmc/argot#5]
grizzled-scala depends on jline and jline depends on JUnit 3.8(!). This is unfortunate because you suddenly have junit 3.8 in your classpath which may be incompatible with another JUnit 4 you want to run your tests with.

Is jline needed for argot or is it just an incidental dependency of grizzled?

**Comment by bmc** [comment]
Closing this issue. Argot is now abandonware. [scopt](https://github.com/scopt/scopt) is more fully-featured and more immutable. That's what I'm switching to using.
